dependencies:
    - smartcontractkit/chainlink-brownie-contracts@0.4.0
    - aave/protocol-v2@1.0.1
compiler:
    solc:
        remappings:
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
            - "@aave=aave/protocol-v2@1.0.1"
networks:
 kovan:
  weth_token: '0xd0A1E359811322d97991E03f863a0C30C2cF029C'
  lending_pool_addresses_provider : '0x88757f2f99175387ab4c6a4b3067c77a695b0349'
  dai_eth_price: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
 mainnet-fork-dev:
  weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
  lending_pool_addresses_provider: '0xb53c1a33016b2dc2ff3653530bff1848a515c8c5'
  dai_eth_price: '0x773616e4d11a78f511299002da57a0a94577f1f4'
wallets:
 from_key: ${PRIVATE_KEY}
dotenv: .env 